/**
 * Bulk aggregates for the employee listing: competency gap status and
 * mandatory training completion percentage per employee.
 */
import { and, eq, inArray, sql } from "drizzle-orm";
import { db, employeesTable, employeeTrainingsTable } from "@workspace/db";
import {
  buildCompetencyKey,
  normalizeCompetencyText,
  resolveEmployeeCompetencies,
  type GapStatus,
} from "./competency-resolver";

type Db = Pick<typeof db, "select">;

// normalizeCompetencyText / buildCompetencyKey moved to competency-resolver.ts
// (Task 2 — resolvedor de competência); reexported here for callers that still
// import them from this module (mirrors the historical location, employees.ts:167–179).
export { buildCompetencyKey, normalizeCompetencyText };

// ─── Public helpers ───────────────────────────────────────────────────────────

/**
 * Mantido por compatibilidade com os call sites existentes. A regra de verdade
 * vive em `resolveEmployeeCompetencies` — este arquivo NÃO reimplementa mais nada.
 *
 * Antes desta mudança havia dois motores de gap discordando: este (relacional) e
 * o `lib/position-requirements.ts` do front (texto livre de `positions.requirements`).
 * A ficha do colaborador podia contradizer o selo da listagem para a mesma pessoa.
 */
export async function computeCompetencyGapStatusByEmployee(
  database: Db,
  orgId: number,
  employees: { id: number; position: string | null }[],
): Promise<Map<number, GapStatus>> {
  const resolved = await resolveEmployeeCompetencies(
    database,
    orgId,
    employees,
  );
  return new Map(
    [...resolved.entries()].map(([employeeId, conf]) => [
      employeeId,
      conf.gapStatus,
    ]),
  );
}

/**
 * For each employee, compute the percentage of mandatory trainings completed
 * up to and including `endOfMonth`.
 *
 * "Mandatory" = `requirementId IS NOT NULL` (generated by the requirements
 * engine in applyTrainingRequirements).
 *
 * Formula (mirrors mandatory_coverage in lms-metrics.ts:245–269, incluindo a
 * exclusão de status = 'nao_aplicavel' do denominador):
 *   total === 0 ? null : Math.round((done / total) * 1000) / 10
 *
 * @returns Map<employeeId, number | null> — employees with no mandatory
 *          trainings are not present in the map (callers use ?? null).
 */
export async function computeTrainingCompletionByEmployee(
  database: Db,
  orgId: number,
  employeeIds: number[],
  endOfMonth: string,
): Promise<Map<number, number | null>> {
  const completionMap = new Map<number, number | null>();

  if (employeeIds.length === 0) return completionMap;

  // Single batch query scoped to the page's employees.
  // Org-scoping is a real guarantee via INNER JOIN to employees filtered by
  // organizationId — mirrors the mandatory_coverage pattern in lms-metrics.ts.
  const rows = await database
    .select({
      employeeId: employeeTrainingsTable.employeeId,
      // "Não aplicável" é invisível para toda contagem de obrigação: fora do
      // numerador (garantido por status = 'concluido') e fora do denominador
      // (excluído aqui) — mirrors mandatory_coverage em lms-metrics.ts.
      total: sql<number>`count(*) filter (where ${employeeTrainingsTable.requirementId} is not null and ${employeeTrainingsTable.status} <> 'nao_aplicavel')`,
      done: sql<number>`count(*) filter (where ${employeeTrainingsTable.requirementId} is not null and ${employeeTrainingsTable.status} = 'concluido' and (${employeeTrainingsTable.completionDate} is null or ${employeeTrainingsTable.completionDate} <= ${endOfMonth}))`,
    })
    .from(employeeTrainingsTable)
    .innerJoin(
      employeesTable,
      eq(employeeTrainingsTable.employeeId, employeesTable.id),
    )
    .where(
      and(
        eq(employeesTable.organizationId, orgId),
        inArray(employeeTrainingsTable.employeeId, employeeIds),
      ),
    )
    .groupBy(employeeTrainingsTable.employeeId);

  for (const row of rows) {
    const total = Number(row.total);
    const done = Number(row.done);
    completionMap.set(
      row.employeeId,
      total === 0 ? null : Math.round((done / total) * 1000) / 10,
    );
  }

  return completionMap;
}
