import { db, questionnaireThemesTable, questionnaireQuestionsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

export async function seedQuestionnaire() {
  const existing = await db.select().from(questionnaireThemesTable).where(eq(questionnaireThemesTable.code, "instalacoes"));
  if (existing.length > 0) return;

  const [theme] = await db.insert(questionnaireThemesTable).values({
    code: "instalacoes",
    name: "Instalações",
    description: "Questões sobre as instalações físicas e infraestrutura da unidade",
    sortOrder: 1,
  }).returning();

  const questions = [
    {
      code: "inst_01",
      questionNumber: "1",
      text: "As atividades da unidade geram a emissão de vibrações contínuas?",
      type: "single_select",
      options: ["Sim", "Não"],
      tags: { "Sim": ["vibracoes_continuas", "instalacoes_vibracoes"] },
      sortOrder: 1,
    },
    {
      code: "inst_02",
      questionNumber: "2",
      text: "Informe a área (metragem) da empresa — área construída e área total do terreno.",
      type: "text",
      options: null,
      tags: null,
      sortOrder: 2,
    },
    {
      code: "inst_03",
      questionNumber: "3",
      text: "Informe a quantidade de colaboradores da empresa — discriminar a quantidade de funcionários próprios e quantidade de terceirizados fixos.",
      type: "text",
      options: null,
      tags: null,
      sortOrder: 3,
    },
    {
      code: "inst_04",
      questionNumber: "4",
      text: "Relate todos os serviços e/ou produtos desenvolvidos pela unidade e, no caso desse último, todas as principais matérias primas utilizadas na fabricação do produto.",
      type: "text",
      options: null,
      tags: null,
      sortOrder: 4,
    },
    {
      code: "inst_05",
      questionNumber: "5",
      text: "Descreva as atividades realizadas pela unidade e produtos ou serviços desenvolvidos/realizados que fazem parte do escopo do sistema de gestão/de compliance da empresa e que deverão ser abrangidas no monitoramento de requisitos legais.",
      type: "text",
      options: null,
      tags: null,
      sortOrder: 5,
    },
    {
      code: "inst_06",
      questionNumber: "6",
      text: "A unidade realiza reformas ou obras de construção civil?",
      type: "single_select",
      options: ["Sim", "Não se aplica"],
      tags: { "Sim": ["construcao_civil", "obras_reformas"] },
      sortOrder: 6,
    },
    {
      code: "inst_07",
      questionNumber: "7",
      text: "Qual tipo de armazenamento/estocagem a unidade utiliza?",
      type: "multi_select",
      options: ["Silos (Aéreo, Bag, de Superfície etc)", "Não se aplica"],
      tags: { "Silos (Aéreo, Bag, de Superfície etc)": ["armazenamento_silos"] },
      sortOrder: 7,
    },
    {
      code: "inst_08",
      questionNumber: "8",
      text: "As instalações são providas de rede pública de água e esgoto?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["rede_publica_agua_esgoto"] },
      sortOrder: 8,
    },
    {
      code: "inst_08_1",
      questionNumber: "8.1",
      text: "Qual a concessionária de serviço público de água e esgoto?",
      type: "single_select",
      options: ["Estadual", "Municipal"],
      conditionalOn: "inst_08",
      conditionalValue: "Sim",
      tags: { "Estadual": ["concessionaria_estadual"], "Municipal": ["concessionaria_municipal"] },
      sortOrder: 9,
    },
    {
      code: "inst_09",
      questionNumber: "9",
      text: "Existem subestações elétricas?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["subestacoes_eletricas", "energia_eletrica"] },
      sortOrder: 10,
    },
    {
      code: "inst_10",
      questionNumber: "10",
      text: "Há transformadores?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["transformadores", "energia_eletrica"] },
      sortOrder: 11,
    },
    {
      code: "inst_11",
      questionNumber: "11",
      text: "Existem atmosferas potencialmente explosivas?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["atmosferas_explosivas", "produtos_quimicos_perigosos"] },
      sortOrder: 12,
    },
    {
      code: "inst_12",
      questionNumber: "12",
      text: "Há geradores de energia à diesel?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["geradores_diesel", "emissoes_atmosfericas", "combustiveis_inflamaveis"] },
      sortOrder: 13,
    },
    {
      code: "inst_13",
      questionNumber: "13",
      text: "A unidade possui consultório odontológico?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["consultorio_odontologico", "saude_trabalhador"] },
      sortOrder: 14,
    },
    {
      code: "inst_14",
      questionNumber: "14",
      text: "A unidade possui ambulatório?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["ambulatorio", "saude_trabalhador"] },
      sortOrder: 15,
    },
    {
      code: "inst_15",
      questionNumber: "15",
      text: "A unidade possui refeitório?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["refeitorio"] },
      sortOrder: 16,
    },
    {
      code: "inst_15_1a",
      questionNumber: "15.1",
      text: "O estabelecimento é enquadrado como:",
      type: "single_select",
      options: ["Cozinha Industrial", "Apenas Área Para Alimentação (sem Preparo de Alimentos)"],
      conditionalOn: "inst_15",
      conditionalValue: "Sim",
      tags: { "Cozinha Industrial": ["cozinha_industrial"], "Apenas Área Para Alimentação (sem Preparo de Alimentos)": ["area_alimentacao"] },
      sortOrder: 17,
    },
    {
      code: "inst_15_1b",
      questionNumber: "15.1b",
      text: "A prestação de serviço de alimentação é terceirizada?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      conditionalOn: "inst_15",
      conditionalValue: "Sim",
      tags: { "Sim": ["alimentacao_terceirizada"] },
      sortOrder: 18,
    },
    {
      code: "inst_16",
      questionNumber: "16",
      text: "A unidade possui laboratório?",
      type: "multi_select",
      options: [
        "Laboratório de Ensaios E/ou Calibração",
        "Laboratório Clínico (análise de Amostras de Paciente/funcionário, Incluindo Exames Exigidos No Pcmso)",
        "Laboratório de Análises Físico-químicas Ou Microbiológica de Potabilidade de Água",
        "Laboratório de Análises Físico-químicas Ou Microbiológica Em Alimentos (incluindo Seus Resíduos, Embalanges, Etc)",
        "Laboratório de Análises Ambientais (emissões Atmosféricas, Efluentes, Solo, Águas Subterrâneas, Superficiais, Etc)",
        "Patologias Clínicas",
        "Não Se Aplica",
      ],
      tags: {
        "Laboratório de Ensaios E/ou Calibração": ["laboratorio_ensaios_calibracao"],
        "Laboratório Clínico (análise de Amostras de Paciente/funcionário, Incluindo Exames Exigidos No Pcmso)": ["laboratorio_clinico", "saude_trabalhador"],
        "Laboratório de Análises Físico-químicas Ou Microbiológica de Potabilidade de Água": ["laboratorio_agua", "recursos_hidricos"],
        "Laboratório de Análises Físico-químicas Ou Microbiológica Em Alimentos (incluindo Seus Resíduos, Embalanges, Etc)": ["laboratorio_alimentos"],
        "Laboratório de Análises Ambientais (emissões Atmosféricas, Efluentes, Solo, Águas Subterrâneas, Superficiais, Etc)": ["laboratorio_ambiental", "emissoes_atmosfericas"],
        "Patologias Clínicas": ["laboratorio_patologia", "saude_trabalhador"],
      },
      sortOrder: 19,
    },
    {
      code: "inst_17",
      questionNumber: "17",
      text: "A unidade possui trabalhadores alojados?",
      type: "single_select",
      options: ["Sim", "Não"],
      tags: { "Sim": ["trabalhadores_alojados"] },
      sortOrder: 20,
    },
    {
      code: "inst_18",
      questionNumber: "18",
      text: "Existem barragens no site da unidade?",
      type: "single_select",
      options: ["Sim", "Somente Reservatório de Água, Represa Ou Lagos Artificiais, Não Caracterizados Como Barragem", "Não Se Aplica"],
      tags: {
        "Sim": ["barragens"],
        "Somente Reservatório de Água, Represa Ou Lagos Artificiais, Não Caracterizados Como Barragem": ["reservatorio_agua"],
      },
      sortOrder: 21,
    },
    {
      code: "inst_19",
      questionNumber: "19",
      text: "Existe alguma área ou instalação na área da unidade alvo de tombamento?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["tombamento_patrimonio"] },
      sortOrder: 22,
    },
    {
      code: "inst_20",
      questionNumber: "20",
      text: "Existe área de armazenamento de contêiner (não considerar IBC's - contetores de plástico)?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["armazenamento_conteiner"] },
      sortOrder: 23,
    },
    {
      code: "inst_21",
      questionNumber: "21",
      text: "A unidade possui heliponto?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["heliponto"] },
      sortOrder: 24,
    },
    {
      code: "inst_22",
      questionNumber: "22",
      text: "Existem escadas rolantes, esteiras ou rampas na empresa?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["escadas_rolantes_esteiras"] },
      sortOrder: 25,
    },
    {
      code: "inst_23",
      questionNumber: "23",
      text: "Na unidade qual a média de circulação/concentração de pessoas?",
      type: "single_select",
      options: [
        "Inferior a 200 pessoas",
        "Entre 201 a 299 Pessoas",
        "Igual Ou Superior A 300 Pessoas",
        "Igual Ou Superior A 500 Pessoas",
        "Igual Ou Superior A 1000 Pessoas",
        "Igual Ou Superior A 1.500 Pessoas",
        "Igual Ou Superior A 2.000 Pessoas",
        "Igual Ou Superior A 5.000 Pessoas",
      ],
      tags: {
        "Igual Ou Superior A 300 Pessoas": ["concentracao_300_mais"],
        "Igual Ou Superior A 500 Pessoas": ["concentracao_300_mais", "concentracao_500_mais"],
        "Igual Ou Superior A 1000 Pessoas": ["concentracao_300_mais", "concentracao_500_mais", "concentracao_1000_mais"],
        "Igual Ou Superior A 1.500 Pessoas": ["concentracao_300_mais", "concentracao_500_mais", "concentracao_1000_mais"],
        "Igual Ou Superior A 2.000 Pessoas": ["concentracao_300_mais", "concentracao_500_mais", "concentracao_1000_mais"],
        "Igual Ou Superior A 5.000 Pessoas": ["concentracao_300_mais", "concentracao_500_mais", "concentracao_1000_mais"],
      },
      sortOrder: 26,
    },
    {
      code: "inst_24",
      questionNumber: "24",
      text: "A unidade realiza atividade de desinfecção e esterilização de produtos ou materiais?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["desinfeccao_esterilizacao", "produtos_quimicos_perigosos"] },
      sortOrder: 27,
    },
    {
      code: "inst_25",
      questionNumber: "25",
      text: "Quais os meios de suspensão ou tração que a unidade utiliza?",
      type: "multi_select",
      options: ["Talhas", "Polia", "Correntes", "Ganchos", "Cabos de Aço", "Outros", "Nenhuma das Anteriores"],
      tags: {
        "Talhas": ["equipamentos_suspensao_tracao"],
        "Polia": ["equipamentos_suspensao_tracao"],
        "Correntes": ["equipamentos_suspensao_tracao"],
        "Ganchos": ["equipamentos_suspensao_tracao"],
        "Cabos de Aço": ["equipamentos_suspensao_tracao"],
        "Outros": ["equipamentos_suspensao_tracao"],
      },
      sortOrder: 28,
    },
    {
      code: "inst_26",
      questionNumber: "26",
      text: "A unidade realiza (ou pode vir a realizar) parcelamento do solo?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["parcelamento_solo"] },
      sortOrder: 29,
    },
    {
      code: "inst_27",
      questionNumber: "27",
      text: "A unidade possui em seu site cercas energizadas/elétricas?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["cercas_eletricas"] },
      sortOrder: 30,
    },
    {
      code: "inst_28",
      questionNumber: "28",
      text: "A unidade realiza atividade que possa ser foco de atração de pássaros em um raio de 20 km de aeroportos que operem por instrumento ou em raio de 13 km de demais aeródromos?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["atracao_passaros_aeroporto", "localizacao_fauna_flora"] },
      sortOrder: 31,
    },
    {
      code: "inst_29",
      questionNumber: "29",
      text: "Existem fontes de ruído na unidade ou são realizadas atividades que possam produzir ruído além dos limites das instalações da empresa?",
      type: "single_select",
      options: ["Sim", "Não Se Aplica"],
      tags: { "Sim": ["ruido_externo", "emissoes_atmosfericas"] },
      sortOrder: 32,
    },
    {
      code: "inst_30",
      questionNumber: "30",
      text: "A unidade possui lagoa de tratamento? (Lagoa de tratamento: toda e qualquer estrutura em solo destinada ao tratamento e/ou armazenamento temporário de efluentes líquidos e de resíduos sólidos gerados por diversas atividades)",
      type: "single_select",
      options: ["Sim", "Não se aplica"],
      tags: { "Sim": ["lagoa_tratamento", "recursos_hidricos_efluentes", "residuos"] },
      sortOrder: 33,
    },
  ];

  for (const q of questions) {
    await db.insert(questionnaireQuestionsTable).values({
      themeId: theme.id,
      code: q.code,
      questionNumber: q.questionNumber,
      text: q.text,
      type: q.type,
      options: q.options,
      conditionalOn: q.conditionalOn || null,
      conditionalValue: q.conditionalValue || null,
      tags: q.tags,
      sortOrder: q.sortOrder,
    });
  }
}
