import { db, questionnaireThemesTable, questionnaireQuestionsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

type QuestionDef = {
  code: string;
  questionNumber: string;
  text: string;
  type: string;
  options: string[] | null;
  tags: Record<string, string[]> | null;
  conditionalOn?: string;
  conditionalValue?: string;
  sortOrder: number;
};

type ThemeDef = {
  code: string;
  name: string;
  description: string;
  sortOrder: number;
  questions: QuestionDef[];
};

async function seedTheme(themeDef: ThemeDef) {
  const existing = await db.select().from(questionnaireThemesTable).where(eq(questionnaireThemesTable.code, themeDef.code));
  if (existing.length > 0) return;

  const [theme] = await db.insert(questionnaireThemesTable).values({
    code: themeDef.code,
    name: themeDef.name,
    description: themeDef.description,
    sortOrder: themeDef.sortOrder,
  }).returning();

  for (const q of themeDef.questions) {
    await db.insert(questionnaireQuestionsTable).values({
      themeId: theme.id,
      code: q.code,
      questionNumber: q.questionNumber,
      text: q.text,
      type: q.type,
      options: q.options,
      conditionalOn: q.conditionalOn || null,
      conditionalValue: q.conditionalValue || null,
      tags: q.tags,
      sortOrder: q.sortOrder,
    });
  }
}

const instalacoes: ThemeDef = {
  code: "instalacoes",
  name: "Instalações",
  description: "Questões sobre as instalações físicas e infraestrutura da unidade",
  sortOrder: 2,
  questions: [
    { code: "inst_01", questionNumber: "1", text: "As atividades da unidade geram a emissão de vibrações contínuas?", type: "single_select", options: ["Sim", "Não"], tags: { "Sim": ["vibracoes_continuas", "instalacoes_vibracoes"] }, sortOrder: 1 },
    { code: "inst_02", questionNumber: "2", text: "Informe a área (metragem) da empresa — área construída e área total do terreno.", type: "text", options: null, tags: null, sortOrder: 2 },
    { code: "inst_03", questionNumber: "3", text: "Informe a quantidade de colaboradores da empresa — discriminar a quantidade de funcionários próprios e quantidade de terceirizados fixos.", type: "text", options: null, tags: null, sortOrder: 3 },
    { code: "inst_04", questionNumber: "4", text: "Relate todos os serviços e/ou produtos desenvolvidos pela unidade e, no caso desse último, todas as principais matérias primas utilizadas na fabricação do produto.", type: "text", options: null, tags: null, sortOrder: 4 },
    { code: "inst_05", questionNumber: "5", text: "Descreva as atividades realizadas pela unidade e produtos ou serviços desenvolvidos/realizados que fazem parte do escopo do sistema de gestão/de compliance da empresa e que deverão ser abrangidas no monitoramento de requisitos legais.", type: "text", options: null, tags: null, sortOrder: 5 },
    { code: "inst_06", questionNumber: "6", text: "A unidade realiza reformas ou obras de construção civil?", type: "single_select", options: ["Sim", "Não se aplica"], tags: { "Sim": ["construcao_civil", "obras_reformas"] }, sortOrder: 6 },
    { code: "inst_07", questionNumber: "7", text: "Qual tipo de armazenamento/estocagem a unidade utiliza?", type: "multi_select", options: ["Silos (Aéreo, Bag, de Superfície etc)", "Não se aplica"], tags: { "Silos (Aéreo, Bag, de Superfície etc)": ["armazenamento_silos"] }, sortOrder: 7 },
    { code: "inst_08", questionNumber: "8", text: "As instalações são providas de rede pública de água e esgoto?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["rede_publica_agua_esgoto"] }, sortOrder: 8 },
    { code: "inst_08_1", questionNumber: "8.1", text: "Qual a concessionária de serviço público de água e esgoto?", type: "single_select", options: ["Estadual", "Municipal"], conditionalOn: "inst_08", conditionalValue: "Sim", tags: { "Estadual": ["concessionaria_estadual"], "Municipal": ["concessionaria_municipal"] }, sortOrder: 9 },
    { code: "inst_09", questionNumber: "9", text: "Existem subestações elétricas?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["subestacoes_eletricas", "energia_eletrica"] }, sortOrder: 10 },
    { code: "inst_10", questionNumber: "10", text: "Há transformadores?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["transformadores", "energia_eletrica"] }, sortOrder: 11 },
    { code: "inst_11", questionNumber: "11", text: "Existem atmosferas potencialmente explosivas?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["atmosferas_explosivas", "produtos_quimicos_perigosos"] }, sortOrder: 12 },
    { code: "inst_12", questionNumber: "12", text: "Há geradores de energia à diesel?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["geradores_diesel", "emissoes_atmosfericas", "combustiveis_inflamaveis"] }, sortOrder: 13 },
    { code: "inst_13", questionNumber: "13", text: "A unidade possui consultório odontológico?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["consultorio_odontologico", "saude_trabalhador"] }, sortOrder: 14 },
    { code: "inst_14", questionNumber: "14", text: "A unidade possui ambulatório?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["ambulatorio", "saude_trabalhador"] }, sortOrder: 15 },
    { code: "inst_15", questionNumber: "15", text: "A unidade possui refeitório?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["refeitorio"] }, sortOrder: 16 },
    { code: "inst_15_1a", questionNumber: "15.1", text: "O estabelecimento é enquadrado como:", type: "single_select", options: ["Cozinha Industrial", "Apenas Área Para Alimentação (sem Preparo de Alimentos)"], conditionalOn: "inst_15", conditionalValue: "Sim", tags: { "Cozinha Industrial": ["cozinha_industrial"], "Apenas Área Para Alimentação (sem Preparo de Alimentos)": ["area_alimentacao"] }, sortOrder: 17 },
    { code: "inst_15_1b", questionNumber: "15.1b", text: "A prestação de serviço de alimentação é terceirizada?", type: "single_select", options: ["Sim", "Não Se Aplica"], conditionalOn: "inst_15", conditionalValue: "Sim", tags: { "Sim": ["alimentacao_terceirizada"] }, sortOrder: 18 },
    { code: "inst_16", questionNumber: "16", text: "A unidade possui laboratório?", type: "multi_select", options: ["Laboratório de Ensaios E/ou Calibração", "Laboratório Clínico (análise de Amostras de Paciente/funcionário, Incluindo Exames Exigidos No Pcmso)", "Laboratório de Análises Físico-químicas Ou Microbiológica de Potabilidade de Água", "Laboratório de Análises Físico-químicas Ou Microbiológica Em Alimentos (incluindo Seus Resíduos, Embalanges, Etc)", "Laboratório de Análises Ambientais (emissões Atmosféricas, Efluentes, Solo, Águas Subterrâneas, Superficiais, Etc)", "Patologias Clínicas", "Não Se Aplica"], tags: { "Laboratório de Ensaios E/ou Calibração": ["laboratorio_ensaios_calibracao"], "Laboratório Clínico (análise de Amostras de Paciente/funcionário, Incluindo Exames Exigidos No Pcmso)": ["laboratorio_clinico", "saude_trabalhador"], "Laboratório de Análises Físico-químicas Ou Microbiológica de Potabilidade de Água": ["laboratorio_agua", "recursos_hidricos"], "Laboratório de Análises Físico-químicas Ou Microbiológica Em Alimentos (incluindo Seus Resíduos, Embalanges, Etc)": ["laboratorio_alimentos"], "Laboratório de Análises Ambientais (emissões Atmosféricas, Efluentes, Solo, Águas Subterrâneas, Superficiais, Etc)": ["laboratorio_ambiental", "emissoes_atmosfericas"], "Patologias Clínicas": ["laboratorio_patologia", "saude_trabalhador"] }, sortOrder: 19 },
    { code: "inst_17", questionNumber: "17", text: "A unidade possui trabalhadores alojados?", type: "single_select", options: ["Sim", "Não"], tags: { "Sim": ["trabalhadores_alojados"] }, sortOrder: 20 },
    { code: "inst_18", questionNumber: "18", text: "Existem barragens no site da unidade?", type: "single_select", options: ["Sim", "Somente Reservatório de Água, Represa Ou Lagos Artificiais, Não Caracterizados Como Barragem", "Não Se Aplica"], tags: { "Sim": ["barragens"], "Somente Reservatório de Água, Represa Ou Lagos Artificiais, Não Caracterizados Como Barragem": ["reservatorio_agua"] }, sortOrder: 21 },
    { code: "inst_19", questionNumber: "19", text: "Existe alguma área ou instalação na área da unidade alvo de tombamento?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["tombamento_patrimonio"] }, sortOrder: 22 },
    { code: "inst_20", questionNumber: "20", text: "Existe área de armazenamento de contêiner (não considerar IBC's - contetores de plástico)?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["armazenamento_conteiner"] }, sortOrder: 23 },
    { code: "inst_21", questionNumber: "21", text: "A unidade possui heliponto?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["heliponto"] }, sortOrder: 24 },
    { code: "inst_22", questionNumber: "22", text: "Existem escadas rolantes, esteiras ou rampas na empresa?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["escadas_rolantes_esteiras"] }, sortOrder: 25 },
    { code: "inst_23", questionNumber: "23", text: "Na unidade qual a média de circulação/concentração de pessoas?", type: "single_select", options: ["Inferior a 200 pessoas", "Entre 201 a 299 Pessoas", "Igual Ou Superior A 300 Pessoas", "Igual Ou Superior A 500 Pessoas", "Igual Ou Superior A 1000 Pessoas", "Igual Ou Superior A 1.500 Pessoas", "Igual Ou Superior A 2.000 Pessoas", "Igual Ou Superior A 5.000 Pessoas"], tags: { "Igual Ou Superior A 300 Pessoas": ["concentracao_300_mais"], "Igual Ou Superior A 500 Pessoas": ["concentracao_300_mais", "concentracao_500_mais"], "Igual Ou Superior A 1000 Pessoas": ["concentracao_300_mais", "concentracao_500_mais", "concentracao_1000_mais"], "Igual Ou Superior A 1.500 Pessoas": ["concentracao_300_mais", "concentracao_500_mais", "concentracao_1000_mais"], "Igual Ou Superior A 2.000 Pessoas": ["concentracao_300_mais", "concentracao_500_mais", "concentracao_1000_mais"], "Igual Ou Superior A 5.000 Pessoas": ["concentracao_300_mais", "concentracao_500_mais", "concentracao_1000_mais"] }, sortOrder: 26 },
    { code: "inst_24", questionNumber: "24", text: "A unidade realiza atividade de desinfecção e esterilização de produtos ou materiais?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["desinfeccao_esterilizacao", "produtos_quimicos_perigosos"] }, sortOrder: 27 },
    { code: "inst_25", questionNumber: "25", text: "Quais os meios de suspensão ou tração que a unidade utiliza?", type: "multi_select", options: ["Talhas", "Polia", "Correntes", "Ganchos", "Cabos de Aço", "Outros", "Nenhuma das Anteriores"], tags: { "Talhas": ["equipamentos_suspensao_tracao"], "Polia": ["equipamentos_suspensao_tracao"], "Correntes": ["equipamentos_suspensao_tracao"], "Ganchos": ["equipamentos_suspensao_tracao"], "Cabos de Aço": ["equipamentos_suspensao_tracao"], "Outros": ["equipamentos_suspensao_tracao"] }, sortOrder: 28 },
    { code: "inst_26", questionNumber: "26", text: "A unidade realiza (ou pode vir a realizar) parcelamento do solo?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["parcelamento_solo"] }, sortOrder: 29 },
    { code: "inst_27", questionNumber: "27", text: "A unidade possui em seu site cercas energizadas/elétricas?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["cercas_eletricas"] }, sortOrder: 30 },
    { code: "inst_28", questionNumber: "28", text: "A unidade realiza atividade que possa ser foco de atração de pássaros em um raio de 20 km de aeroportos que operem por instrumento ou em raio de 13 km de demais aeródromos?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["atracao_passaros_aeroporto", "localizacao_fauna_flora"] }, sortOrder: 31 },
    { code: "inst_29", questionNumber: "29", text: "Existem fontes de ruído na unidade ou são realizadas atividades que possam produzir ruído além dos limites das instalações da empresa?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["ruido_externo", "emissoes_atmosfericas"] }, sortOrder: 32 },
    { code: "inst_30", questionNumber: "30", text: "A unidade possui lagoa de tratamento? (Lagoa de tratamento: toda e qualquer estrutura em solo destinada ao tratamento e/ou armazenamento temporário de efluentes líquidos e de resíduos sólidos gerados por diversas atividades)", type: "single_select", options: ["Sim", "Não se aplica"], tags: { "Sim": ["lagoa_tratamento", "recursos_hidricos_efluentes", "residuos"] }, sortOrder: 33 },
  ],
};

const produtosInsumos: ThemeDef = {
  code: "produtos_insumos",
  name: "Produtos, Insumos e Demais Substâncias",
  description: "Questões sobre produtos pré-medidos, importação/exportação, transgênicos e conformidade INMETRO",
  sortOrder: 4,
  questions: [
    { code: "pi_01", questionNumber: "1", text: "A unidade fabrica produtos pré-medidos?", type: "single_select", options: ["Sim", "Não se aplica"], tags: { "Sim": ["produtos_pre_medidos", "inmetro"] }, sortOrder: 1 },
    { code: "pi_02", questionNumber: "2", text: "A unidade realiza atividades de importação e/ou exportação? (Aplicável às unidades que efetuam operações comerciais internacionais de compra e/ou venda de produtos, insumos ou equipamentos, ainda que utilizem recintos alfandegados de terceiros para desembaraço ou embarque de mercadorias.)", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["importacao_exportacao", "comercio_internacional"] }, sortOrder: 2 },
    { code: "pi_03", questionNumber: "3", text: "A unidade fabrica ou utiliza produtos transgênicos?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["produtos_transgenicos", "biosseguranca"] }, sortOrder: 3 },
    { code: "pi_04", questionNumber: "4", text: "A unidade fabrica, comercializa ou utiliza produtos sujeitos à avaliação da conformidade pelo INMETRO ou organismo acreditado?", type: "multi_select", options: ["Fabrica", "Comercializa", "Utiliza", "Não Se Aplica"], tags: { "Fabrica": ["inmetro_fabrica", "avaliacao_conformidade"], "Comercializa": ["inmetro_comercializa", "avaliacao_conformidade"], "Utiliza": ["inmetro_utiliza", "avaliacao_conformidade"] }, sortOrder: 4 },
  ],
};

const produtosFlorestais: ThemeDef = {
  code: "produtos_florestais",
  name: "Produtos e Subprodutos Florestais",
  description: "Questões sobre produção orgânica, produtos florestais, carvão vegetal, madeira e fitossanidade",
  sortOrder: 5,
  questions: [
    { code: "pf_01", questionNumber: "1", text: "A unidade possui sistema orgânico de produção?", type: "single_select", options: ["Sim", "Não se aplica"], tags: { "Sim": ["producao_organica", "produtos_florestais"] }, sortOrder: 1 },
    { code: "pf_02", questionNumber: "2", text: "A unidade realiza o plantio, consome/explora ou utiliza produtos (estado bruto ou in natura) e subprodutos (submetido a processo de beneficiamento) florestais?", type: "multi_select", options: ["Não Se Aplica", "Consome ou realiza plantio de Produtos de Origem Nativa", "Consome ou realiza plantio de Produtos de Origem Plantada/exótica", "Consome Subprodutos de Origem Nativa", "Consome Subprodutos de Origem Plantada/exótica", "Apenas Consome Ou Utiliza Palletes de Madeira Plantada/exótica", "Apenas Consome Ou Utiliza Palletes de Madeira Nativa", "Apenas Consome Ou Utiliza Outros Subprodutos de Madeira Acabados, Exceto Palletes (exemplo: Portas, Janelas, Mobiliário, Etc.)", "Realiza Exploração de Florestas Sob Regime de Concessão Federal E/ou Estadual.", "Realiza Exploração Econômica de Produto Acabado Ou Material Reprodutivo Oriundo de Acesso Ao Patrimônio Genético Ou Ao Conhecimento Tradicional Associado"], tags: { "Consome ou realiza plantio de Produtos de Origem Nativa": ["produtos_florestais_nativos", "ibama"], "Consome ou realiza plantio de Produtos de Origem Plantada/exótica": ["produtos_florestais_plantados"], "Consome Subprodutos de Origem Nativa": ["subprodutos_florestais_nativos", "ibama"], "Consome Subprodutos de Origem Plantada/exótica": ["subprodutos_florestais_plantados"], "Apenas Consome Ou Utiliza Palletes de Madeira Plantada/exótica": ["paletes_madeira_plantada"], "Apenas Consome Ou Utiliza Palletes de Madeira Nativa": ["paletes_madeira_nativa", "ibama"], "Apenas Consome Ou Utiliza Outros Subprodutos de Madeira Acabados, Exceto Palletes (exemplo: Portas, Janelas, Mobiliário, Etc.)": ["subprodutos_madeira_acabados"], "Realiza Exploração de Florestas Sob Regime de Concessão Federal E/ou Estadual.": ["concessao_florestal", "ibama"], "Realiza Exploração Econômica de Produto Acabado Ou Material Reprodutivo Oriundo de Acesso Ao Patrimônio Genético Ou Ao Conhecimento Tradicional Associado": ["patrimonio_genetico", "conhecimento_tradicional"] }, sortOrder: 2 },
    { code: "pf_03", questionNumber: "3", text: "A unidade consome ou transporta carvão vegetal?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["carvao_vegetal", "produtos_florestais"] }, sortOrder: 3 },
    { code: "pf_04", questionNumber: "4", text: "É realizada importação e/ou exportação de produtos e subprodutos madeireiros?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["importacao_exportacao_madeira", "comercio_internacional"] }, sortOrder: 4 },
    { code: "pf_05", questionNumber: "5", text: "A unidade realiza importação ou exportação de produtos embalados em madeira?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["embalagem_madeira", "comercio_internacional", "fitossanidade"] }, sortOrder: 5 },
    { code: "pf_06", questionNumber: "6", text: "A unidade importa ou exporta produtos sujeitos a controle de requisitos fitossanitários?", type: "multi_select", options: ["Não Se Aplica", "Produtos Em Paletes Ou Outras Embalagens de Madeira", "Produtos Vegetais Tais Como Madeira, Mudas, Sementes, Frutos, Etc."], tags: { "Produtos Em Paletes Ou Outras Embalagens de Madeira": ["fitossanidade_embalagem_madeira", "comercio_internacional"], "Produtos Vegetais Tais Como Madeira, Mudas, Sementes, Frutos, Etc.": ["fitossanidade_vegetais", "comercio_internacional"] }, sortOrder: 6 },
    { code: "pf_07", questionNumber: "7", text: "A unidade utiliza e/ou comercializa mudas?", type: "multi_select", options: ["Utiliza", "Comercializa", "Não Se Aplica"], tags: { "Utiliza": ["mudas_utiliza", "produtos_florestais"], "Comercializa": ["mudas_comercializa", "produtos_florestais"] }, sortOrder: 7 },
    { code: "pf_08", questionNumber: "8", text: "Há exigência de plano de manejo florestal sustentável para a área da unidade?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["manejo_florestal", "ibama"] }, sortOrder: 8 },
    { code: "pf_09", questionNumber: "9", text: "A unidade realiza ou contrata o transporte rodoviário de toras ou madeira bruta?", type: "multi_select", options: ["Realiza", "Contrata / Adquire de Terceiros", "Não Se Aplica"], tags: { "Realiza": ["transporte_madeira_bruta", "produtos_florestais"], "Contrata / Adquire de Terceiros": ["transporte_madeira_terceiros", "produtos_florestais"] }, sortOrder: 9 },
  ],
};

const combustiveisInflamaveis: ThemeDef = {
  code: "combustiveis_inflamaveis",
  name: "Combustíveis e Inflamáveis",
  description: "Questões sobre armazenamento de combustíveis, GLP, gás natural, postos de abastecimento e GNV",
  sortOrder: 6,
  questions: [
    { code: "ci_01", questionNumber: "1", text: "A unidade possui armazenamento de combustíveis e inflamáveis?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["armazenamento_combustiveis", "combustiveis_inflamaveis"] }, sortOrder: 1 },
    { code: "ci_01_1", questionNumber: "1.1", text: "O armazenamento é em recipientes estacionários ou em transportáveis?", type: "multi_select", options: ["Estacionários", "Transportáveis"], conditionalOn: "ci_01", conditionalValue: "Sim", tags: { "Estacionários": ["tanques_estacionarios", "combustiveis_inflamaveis"], "Transportáveis": ["recipientes_transportaveis", "combustiveis_inflamaveis"] }, sortOrder: 2 },
    { code: "ci_01_2", questionNumber: "1.2", text: "Se em tanque, o mesmo é aéreo ou subterrâneo?", type: "multi_select", options: ["Aéreo Até 15 M³", "Subterrâneo", "Aéreo Acima de 15 M³", "Não Se Aplica"], conditionalOn: "ci_01", conditionalValue: "Sim", tags: { "Aéreo Até 15 M³": ["tanque_aereo_pequeno", "combustiveis_inflamaveis"], "Subterrâneo": ["tanque_subterraneo", "combustiveis_inflamaveis"], "Aéreo Acima de 15 M³": ["tanque_aereo_grande", "combustiveis_inflamaveis"] }, sortOrder: 3 },
    { code: "ci_02", questionNumber: "2", text: "A unidade utiliza GLP - Gás Liquefeito de Petróleo ou Gás Natural?", type: "multi_select", options: ["GLP - Gás Liquefeito de Petróleo", "Gás Natural", "Não Se Aplica"], tags: { "GLP - Gás Liquefeito de Petróleo": ["glp", "combustiveis_inflamaveis"], "Gás Natural": ["gas_natural", "combustiveis_inflamaveis"] }, sortOrder: 4 },
    { code: "ci_02_1", questionNumber: "2.1", text: "O armazenamento de GLP ocorre em recipientes transportáveis ou estacionários?", type: "multi_select", options: ["Não há armazenamento em reservatório", "Transportáveis", "Estacionários"], conditionalOn: "ci_02", conditionalValue: "GLP - Gás Liquefeito de Petróleo", tags: { "Transportáveis": ["glp_transportavel"], "Estacionários": ["glp_estacionario"] }, sortOrder: 5 },
    { code: "ci_03", questionNumber: "3", text: "A unidade faz uso de instalações de transporte dutoviário de gás natural?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["transporte_dutoviario_gas", "gas_natural"] }, sortOrder: 6 },
    { code: "ci_04", questionNumber: "4", text: "Há posto de abastecimento de combustíveis automotivos na unidade?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["posto_abastecimento", "combustiveis_inflamaveis"] }, sortOrder: 7 },
    { code: "ci_04_1", questionNumber: "4.1", text: "Como é o armazenamento de combustível no posto?", type: "multi_select", options: ["Aéreo", "Subterrâneo"], conditionalOn: "ci_04", conditionalValue: "Sim", tags: { "Aéreo": ["posto_tanque_aereo"], "Subterrâneo": ["posto_tanque_subterraneo"] }, sortOrder: 8 },
    { code: "ci_05", questionNumber: "5", text: "A unidade utiliza gás natural veicular (GNV) em sua frota de veículos?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["gnv", "gas_natural", "combustiveis_inflamaveis"] }, sortOrder: 9 },
  ],
};

const produtosQuimicos: ThemeDef = {
  code: "produtos_quimicos",
  name: "Produtos Químicos E/ou Perigosos",
  description: "Questões sobre manuseio, armazenamento, fabricação, importação e comercialização de produtos químicos e perigosos",
  sortOrder: 7,
  questions: [
    { code: "pq_01", questionNumber: "1", text: "A unidade possui equipamento (transformador, capacitor) contaminado por Ascarel / Bifenilas Policloradas (ou óleos contaminados por PCB em teores maiores que 50 ppm)?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["ascarel_pcb", "produtos_quimicos_perigosos"] }, sortOrder: 1 },
    { code: "pq_02", questionNumber: "2", text: "Existe atividade ou situação na empresa em que gere exposição ocupacional dos trabalhadores ao amianto?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["exposicao_amianto", "saude_trabalhador"] }, sortOrder: 2 },
    { code: "pq_03", questionNumber: "3", text: "A unidade gera resíduos de amianto ou possui em suas edificações telhas ou caixa d'água de amianto?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["residuos_amianto", "residuos"] }, sortOrder: 3 },
    { code: "pq_04", questionNumber: "4", text: "É feito uso de explosivo?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["explosivos", "produtos_quimicos_perigosos"] }, sortOrder: 4 },
    { code: "pq_05", questionNumber: "5", text: "A unidade importa solventes?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["importacao_solventes", "produtos_quimicos_perigosos"] }, sortOrder: 5 },
    { code: "pq_06", questionNumber: "6", text: "A unidade utiliza pilhas e baterias?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["pilhas_baterias", "logistica_reversa"] }, sortOrder: 6 },
    { code: "pq_07", questionNumber: "7", text: "Existem poluentes orgânicos persistentes - POP's no processo da unidade?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["poluentes_organicos_persistentes", "produtos_quimicos_perigosos"] }, sortOrder: 7 },
    { code: "pq_08", questionNumber: "8", text: "A unidade realiza testes com combustíveis não especificados?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["testes_combustiveis", "combustiveis_inflamaveis"] }, sortOrder: 8 },
    { code: "pq_09", questionNumber: "9", text: "A unidade utiliza algum produto classificado como remediador?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["produto_remediador", "produtos_quimicos_perigosos"] }, sortOrder: 9 },
    { code: "pq_10", questionNumber: "10", text: "Os trabalhadores estão sujeitos a exposição ocupacional de produtos químicos que contenham benzeno?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["exposicao_benzeno", "saude_trabalhador"] }, sortOrder: 10 },
    { code: "pq_11", questionNumber: "11", text: "A unidade faz uso de substância controlada pelo Protocolo de Montreal?", type: "multi_select", options: ["Utiliza substâncias controladas como matéria-prima no processo produtivo, na manufatura de equipamentos, tratamento fitossanitário para fins de exportação e importação e em usos laboratoriais, farmacêuticos e afins", "Utiliza em aparelhos de ar condicionado ou de refrigeração", "Não Se Aplica"], tags: { "Utiliza substâncias controladas como matéria-prima no processo produtivo, na manufatura de equipamentos, tratamento fitossanitário para fins de exportação e importação e em usos laboratoriais, farmacêuticos e afins": ["protocolo_montreal_materia_prima"], "Utiliza em aparelhos de ar condicionado ou de refrigeração": ["protocolo_montreal_refrigeracao"] }, sortOrder: 11 },
    { code: "pq_12", questionNumber: "12", text: "A unidade produz produtos biológicos terminados?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["produtos_biologicos", "anvisa"] }, sortOrder: 12 },
    { code: "pq_13", questionNumber: "13", text: "A unidade produz ou importa drogas, medicamentos, produtos intermediários e/ou insumos farmacêuticos?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["medicamentos_farmaceuticos", "anvisa"] }, sortOrder: 13 },
    { code: "pq_14", questionNumber: "14", text: "A unidade comercializa/utiliza produtos pré-medidos, sob a forma de aerossol?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["aerossol", "produtos_quimicos_perigosos"] }, sortOrder: 14 },
    { code: "pq_15", questionNumber: "15", text: "A unidade fabrica e/ou importa produtos de higiene pessoal, cosméticos e perfumes?", type: "multi_select", options: ["Importa", "Fabrica", "Não Se Aplica"], tags: { "Importa": ["importacao_cosmeticos", "anvisa"], "Fabrica": ["fabricacao_cosmeticos", "anvisa"] }, sortOrder: 15 },
    { code: "pq_16", questionNumber: "16", text: "A unidade fabrica e/ou realiza análise de eficácia de medicamentos?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["analise_medicamentos", "anvisa"] }, sortOrder: 16 },
    { code: "pq_17", questionNumber: "17", text: "A unidade possui área com potencial ou suspeita de contaminação das águas superficiais, subterrâneas, do solo ou realiza atividades que possam gerar tal contaminação?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["contaminacao_solo_agua", "recursos_hidricos", "residuos"] }, sortOrder: 17 },
    { code: "pq_18", questionNumber: "18", text: "Indique quais os produtos a unidade fabrica/produz:", type: "multi_select", options: ["Biometano", "Negro de Fumo", "Produtos veterinários", "Saneantes", "Solventes controlados pela Polícia Federal com concentração acima de 60%", "Chumbo", "Soda Cáustica", "Ácido Fluorídrico", "Nitrato de Amônio", "Mercúrio", "Solventes", "Cola de Sapateiro, Adesivos Ou Corretivos", "Thiner", "Tolueno", "Cloro", "Detergente em pó", "Benzeno", "Fertilizantes", "Controlados Pela Polícia Civil", "Controlados Pela Polícia Federal", "Controlados Pelo Exército", "Biodiesel", "Gás Natural", "Glp - Gás Liquefeito de Petróleo", "Agrotóxicos", "Óleo Lubrificante", "Óleo Diesel", "Medicamentos, Drogas, Insumos Farmacêuticos e Afins", "Produtos Para Controle de Pragas e Vetores", "Produtos Para Higienização E/ou Desinfecção", "Pilha/Bateria", "Metanol", "Pneu", "Não Se Aplica"], tags: { "Agrotóxicos": ["fabrica_agrotoxicos"], "Benzeno": ["fabrica_benzeno"], "Biodiesel": ["fabrica_biodiesel"], "Controlados Pelo Exército": ["fabrica_controlados_exercito"], "Controlados Pela Polícia Federal": ["fabrica_controlados_pf"], "Controlados Pela Polícia Civil": ["fabrica_controlados_pc"], "Medicamentos, Drogas, Insumos Farmacêuticos e Afins": ["fabrica_medicamentos"], "Solventes controlados pela Polícia Federal com concentração acima de 60%": ["fabrica_solventes_controlados"] }, sortOrder: 18 },
    { code: "pq_19", questionNumber: "19", text: "Indique quais os produtos a unidade importa:", type: "multi_select", options: ["Produtos veterinários", "Saneantes", "Solventes controlados pela Polícia Federal com concentração acima de 60%", "Solventes", "Cola de Sapateiro, Adesivos Ou Corretivos", "Thiner", "Tolueno", "Cloro", "Mercúrio", "Nitrato de Amônio", "Ácido Fluorídrico", "Chumbo", "Óleo Lubrificante", "Agrotóxicos", "Domissanitários", "Glp - Gás Liquefeito de Petróleo", "Gás Natural", "Biodiesel", "Controlados Pelo Exército", "Controlados Pela Polícia Federal", "Controlados Pela Polícia Civil", "Fertilizantes", "Benzeno", "Soda Cáustica", "Pilha/bateria", "Pneu", "Óleo Diesel", "Medicamentos, Drogas, Insumos Farmacêuticos e Afins", "Produtos Para Controle de Pragas e Vetores", "Produtos Para Higienização E/ou Desinfecção", "Não Se Aplica"], tags: { "Agrotóxicos": ["importa_agrotoxicos"], "Controlados Pelo Exército": ["importa_controlados_exercito"], "Controlados Pela Polícia Federal": ["importa_controlados_pf"], "Medicamentos, Drogas, Insumos Farmacêuticos e Afins": ["importa_medicamentos"] }, sortOrder: 19 },
    { code: "pq_20", questionNumber: "20", text: "Indique quais os produtos químicos a unidade comercializa:", type: "multi_select", options: ["Biometano", "Produtos veterinários", "Saneantes", "Solventes controlados pela Polícia Federal com concentração acima de 60%", "Solventes", "Cola de Sapateiro, Adesivos Ou Corretivos", "Thiner", "Tolueno", "Cloro", "Mercúrio", "Nitrato de Amônio", "Ácido Fluorídrico", "Soda Cáustica", "Chumbo", "Óleo Lubrificante", "Agrotóxicos", "Domissanitários", "Glp - Gás Liquefeito de Petróleo", "Gás Natural", "Biodiesel", "Controlados Pelo Exército", "Controlados Pela Polícia Federal", "Controlados Pela Polícia Civil", "Fertilizantes", "Benzeno", "Óleo Diesel", "Medicamentos, Drogas, Insumos Farmacêuticos e Afins", "Produtos Para Controle de Pragas e Vetores", "Produtos Para Higienização E/ou Desinfecção", "Pilha/Bateria", "Metanol", "Pneu", "Não Se Aplica"], tags: { "Agrotóxicos": ["comercializa_agrotoxicos"], "Controlados Pelo Exército": ["comercializa_controlados_exercito"], "Controlados Pela Polícia Federal": ["comercializa_controlados_pf"], "Medicamentos, Drogas, Insumos Farmacêuticos e Afins": ["comercializa_medicamentos"] }, sortOrder: 20 },
    { code: "pq_21", questionNumber: "21", text: "Indique quais os produtos a unidade armazena:", type: "multi_select", options: ["Não Se Aplica", "Pneu", "Metanol", "Pilha/Bateria", "Produtos Para Higienização E/ou Desinfecção", "Produtos Para Controle de Pragas e Vetores", "Medicamentos, Drogas, Insumos Farmacêuticos e Afins", "Óleo Diesel", "Óleo Lubrificante", "Agrotóxicos", "Glp - Gás Liquefeito de Petróleo", "Gás Natural", "Biodiesel", "Controlados Pelo Exército", "Controlados Pela Polícia Federal", "Controlados Pela Polícia Civil", "Fertilizantes", "Benzeno", "Detergente em pó", "Cloro", "Tolueno", "Thiner", "Cola de Sapateiro, Adesivos Ou Corretivos", "Solventes", "Mercúrio", "Nitrato de Amônio", "Ácido Fluorídrico", "Soda Cáustica", "Biometano", "Negro de Fumo", "Produtos veterinários", "Saneantes", "Solventes controlados pela Polícia Federal com concentração acima de 60%", "Chumbo"], tags: { "Agrotóxicos": ["armazena_agrotoxicos"], "Controlados Pelo Exército": ["armazena_controlados_exercito"], "Controlados Pela Polícia Federal": ["armazena_controlados_pf"], "Medicamentos, Drogas, Insumos Farmacêuticos e Afins": ["armazena_medicamentos"] }, sortOrder: 21 },
    { code: "pq_22", questionNumber: "22", text: "Indique quais os produtos químicos a unidade utiliza:", type: "multi_select", options: ["Biometano", "Negro de Fumo", "Produtos veterinários", "Saneantes", "Solventes controlados pela Polícia Federal com concentração acima de 60%", "Chumbo", "Mercúrio", "Cloro/Ácido clorídrico, desde que puro (não considerar produtos para limpeza, tratamento de água que são comercialmente diluídos).", "Cola de Sapateiro, Adesivos Ou Corretivos", "Thiner", "Tolueno", "Solventes", "Ácido Fluorídrico", "Soda Cáustica", "Óleo Lubrificante", "Agrotóxicos", "Glp - Gás Liquefeito de Petróleo", "Gás Natural", "Biodiesel", "Controlados Pelo Exército (consultar Portaria COLOG Nº 118, de 04-10-2019)", "Controlados Pela Polícia Federal (consultar anexos da PORTARIA MJSP Nº 204, DE 21-10-2022)", "Controlados Pela Polícia Civil (somente em alguns estados como São Paulo, possuem listagem específica. Em caso de dúvidas, abrir um chamado.)", "Fertilizantes", "Benzeno", "Perigosos (conforme FDS/Fispq do Produto)", "Óleos Combustíveis", "Óleo Diesel", "Nitrato de Amônio", "Produtos Para Controle de Pragas e Vetores", "Medicamentos, Drogas, Insumos Farmacêuticos e Afins", "Produtos Para Higienização E/ou Desinfecção", "Metanol", "Não Se Aplica"], tags: { "Agrotóxicos": ["utiliza_agrotoxicos"], "Benzeno": ["utiliza_benzeno"], "Perigosos (conforme FDS/Fispq do Produto)": ["utiliza_perigosos_fds"], "Controlados Pelo Exército (consultar Portaria COLOG Nº 118, de 04-10-2019)": ["utiliza_controlados_exercito"], "Controlados Pela Polícia Federal (consultar anexos da PORTARIA MJSP Nº 204, DE 21-10-2022)": ["utiliza_controlados_pf"] }, sortOrder: 22 },
    { code: "pq_22_1", questionNumber: "22.1", text: "A unidade utiliza solventes como matéria-prima para uso em seu processo produtivo?", type: "single_select", options: ["Sim", "Não Se Aplica"], conditionalOn: "pq_22", conditionalValue: "Solventes", tags: { "Sim": ["solventes_materia_prima"] }, sortOrder: 23 },
    { code: "pq_23", questionNumber: "23", text: "A transportadora de resíduos/produtos perigosos contratada pela unidade realiza esse transporte somente dentro do estado que se encontra?", type: "single_select", options: ["Sim", "Não, A Transportadora Transita Em Outros Estados.", "Não Se Aplica"], tags: { "Sim": ["transporte_perigosos_intraestadual"], "Não, A Transportadora Transita Em Outros Estados.": ["transporte_perigosos_interestadual"] }, sortOrder: 24 },
  ],
};

const recursosHidricos: ThemeDef = {
  code: "recursos_hidricos",
  name: "Recursos Hídricos / Efluentes Líquidos",
  description: "Questões sobre captação de água, efluentes, tratamento, outorga e bacias hidrográficas",
  sortOrder: 8,
  questions: [
    { code: "rh_01", questionNumber: "1", text: "A unidade está localizada em área de proteção a mananciais?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["protecao_mananciais", "recursos_hidricos"] }, sortOrder: 1 },
    { code: "rh_02", questionNumber: "2", text: "Há curso de água próximo ao site da empresa, de forma que haja intervenção ou interação com o mesmo?", type: "single_select", options: ["Não Se Aplica", "A Mais de 200 M", "A Menos de 200 M"], tags: { "A Menos de 200 M": ["curso_agua_proximo", "recursos_hidricos"], "A Mais de 200 M": ["curso_agua_distante"] }, sortOrder: 2 },
    { code: "rh_03", questionNumber: "3", text: "A unidade faz uso de recursos hídricos sujeito a outorga?", type: "multi_select", options: ["Sim", "Não Se Aplica", "Derivação Ou Captação de Parcela da Água Existente Em Um Corpo de Água Para Consumo Final, Inclusive Abastecimento Público, Ou Insumo de Processo Produtivo.", "Extração de Água de Aqüífero Subterrâneo Para Consumo Final Ou Insumo de Processo Produtivo.", "Lançamento Em Corpo de Água de Esgotos e Demais Resíduos Líquidos Ou Gasosos, Tratados Ou Não, Com O Fim de Sua Diluição, Transporte Ou Disposição Final.", "Aproveitamento dos Potenciais Hidrelétricos.", "Outros Usos Que Alterem O Regime, A Quantidade Ou A Qualidade da Água Existente Em Um Corpo de Água.", "Usos Insignificantes de Recursos Hídricos (Obs: O critério de caracterização varia de acordo com o estado. Para captação em corpos da União, consultar a Resolução ANA nº 236/2024 e alterações.)"], tags: { "Derivação Ou Captação de Parcela da Água Existente Em Um Corpo de Água Para Consumo Final, Inclusive Abastecimento Público, Ou Insumo de Processo Produtivo.": ["outorga_captacao_superficial"], "Extração de Água de Aqüífero Subterrâneo Para Consumo Final Ou Insumo de Processo Produtivo.": ["outorga_captacao_subterranea"], "Lançamento Em Corpo de Água de Esgotos e Demais Resíduos Líquidos Ou Gasosos, Tratados Ou Não, Com O Fim de Sua Diluição, Transporte Ou Disposição Final.": ["outorga_lancamento_efluentes"], "Aproveitamento dos Potenciais Hidrelétricos.": ["outorga_hidreletrico"] }, sortOrder: 3 },
    { code: "rh_04", questionNumber: "4", text: "Indique qual(is) bacia(s) hidrográfica(s) a unidade está localizada:", type: "multi_select", options: ["Não se aplica", "Outros", "Bacia Hidrográfica do Rio Uruguai", "Bacia Hidrográfica do Rio São Francisco", "Bacia Hidrográfica do Rio Paraíba do Sul", "Bacia Hidrográfica dos Rios Tocantins e Araguaia", "Bacia Hidrográfica Amazônica", "Bacia Hidrográfica Platina", "Bacia Hidrográfica do Rio Doce Região Hidrográfica do Rio Barra Seca", "Bacias Hidrográficas dos Rios Piracicaba, Capivari e Jundiaí", "Bacia hidrográfica do Alto Tietê", "Bacia Hidrográfica do Rio Gravataí", "Bacia Hidrográfica do Rio Das Velhas"], tags: { "Bacia Hidrográfica do Rio São Francisco": ["bacia_sao_francisco"], "Bacia Hidrográfica do Rio Paraíba do Sul": ["bacia_paraiba_sul"], "Bacia Hidrográfica do Rio Uruguai": ["bacia_uruguai"] }, sortOrder: 4 },
    { code: "rh_05", questionNumber: "5", text: "A unidade realiza captação de recursos hídricos?", type: "multi_select", options: ["Não Se Aplica", "Curso D'água Superficial", "Curso D'água Subterrâneo"], tags: { "Curso D'água Superficial": ["captacao_superficial", "recursos_hidricos"], "Curso D'água Subterrâneo": ["captacao_subterranea", "recursos_hidricos"] }, sortOrder: 5 },
    { code: "rh_06", questionNumber: "6", text: "Existem bebedouros na unidade?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["bebedouros"] }, sortOrder: 6 },
    { code: "rh_06_1", questionNumber: "6.1", text: "Os bebedouros são classificados como:", type: "multi_select", options: ["Equipamentos Tradicionalmente Classificado Como Bebedouros", "Pontos de Fornecimento de Água Mineral Envasada Em Galões"], conditionalOn: "rh_06", conditionalValue: "Sim", tags: { "Equipamentos Tradicionalmente Classificado Como Bebedouros": ["bebedouros_tradicionais"], "Pontos de Fornecimento de Água Mineral Envasada Em Galões": ["agua_mineral_galoes"] }, sortOrder: 7 },
    { code: "rh_07", questionNumber: "7", text: "A unidade gera efluentes líquidos e os encaminha para posterior destinação direta ou indireta em corpo hídrico, ou realiza por conta própria o lançamento (direto ou indireto) de efluentes líquidos em curso d'água?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["lancamento_efluentes_corpo_hidrico", "recursos_hidricos"] }, sortOrder: 8 },
    { code: "rh_08", questionNumber: "8", text: "A unidade realiza o lançamento direto ou indireto de efluentes líquidos (não domésticos) em rede pública de esgoto?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["efluentes_rede_publica"] }, sortOrder: 9 },
    { code: "rh_09", questionNumber: "9", text: "A unidade faz captação da água da chuva?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["captacao_agua_chuva"] }, sortOrder: 10 },
    { code: "rh_10", questionNumber: "10", text: "A unidade contrata caminhão pipa?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["caminhao_pipa"] }, sortOrder: 11 },
    { code: "rh_11", questionNumber: "11", text: "Há estação de tratamento de efluentes industriais?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["ete_industrial", "recursos_hidricos"] }, sortOrder: 12 },
    { code: "rh_12", questionNumber: "12", text: "Existe estação de tratamento de esgoto sanitário?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["ete_sanitario", "recursos_hidricos"] }, sortOrder: 13 },
    { code: "rh_13", questionNumber: "13", text: "Há estação de tratamento de água?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["eta", "recursos_hidricos"] }, sortOrder: 14 },
    { code: "rh_14", questionNumber: "14", text: "Há caixas separadoras de água e óleo?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["caixa_separadora_agua_oleo"] }, sortOrder: 15 },
    { code: "rh_15", questionNumber: "15", text: "A unidade possui fossa séptica?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["fossa_septica"] }, sortOrder: 16 },
    { code: "rh_16", questionNumber: "16", text: "A unidade reutiliza água?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["reuso_agua", "recursos_hidricos"] }, sortOrder: 17 },
    { code: "rh_17", questionNumber: "17", text: "A unidade possui sistema de irrigação agrícola?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["irrigacao_agricola", "recursos_hidricos"] }, sortOrder: 18 },
  ],
};

const residuos: ThemeDef = {
  code: "residuos",
  name: "Resíduos",
  description: "Questões sobre geração, destinação, logística reversa e gestão de resíduos sólidos",
  sortOrder: 9,
  questions: [
    { code: "res_01", questionNumber: "1", text: "A unidade está sujeita a implementação da logística reversa?", type: "multi_select", options: ["Consumidores", "Comerciantes", "Distribuidores", "Fabricantes", "Importadores", "Não se aplica"], tags: { "Consumidores": ["logistica_reversa_consumidor"], "Comerciantes": ["logistica_reversa_comerciante"], "Distribuidores": ["logistica_reversa_distribuidor"], "Fabricantes": ["logistica_reversa_fabricante"], "Importadores": ["logistica_reversa_importador"] }, sortOrder: 1 },
    { code: "res_02", questionNumber: "2", text: "A unidade realiza coleta de lixo seletiva?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["coleta_seletiva", "residuos"] }, sortOrder: 2 },
    { code: "res_03", questionNumber: "3", text: "A unidade envia resíduos para co-processamento ou possui fornos de clínquer?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["coprocessamento", "residuos"] }, sortOrder: 3 },
    { code: "res_04", questionNumber: "4", text: "A unidade envia resíduos para incineração?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["incineracao_residuos", "residuos"] }, sortOrder: 4 },
    { code: "res_05", questionNumber: "5", text: "A unidade envia resíduos para aterro?", type: "multi_select", options: ["Aterro Sanitário", "Aterro Controlado", "Lixão", "Não Se Aplica", "Aterro Industrial"], tags: { "Aterro Sanitário": ["aterro_sanitario"], "Aterro Controlado": ["aterro_controlado"], "Lixão": ["lixao"], "Aterro Industrial": ["aterro_industrial"] }, sortOrder: 5 },
    { code: "res_06", questionNumber: "6", text: "A unidade gera resíduos de serviço de saúde (ambulatoriais)?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["residuos_saude", "residuos"] }, sortOrder: 6 },
    { code: "res_07", questionNumber: "7", text: "A unidade gera resíduos de óleo lubrificante?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["residuos_oleo_lubrificante", "residuos"] }, sortOrder: 7 },
    { code: "res_08", questionNumber: "8", text: "A unidade realiza ou encaminha resíduos para compostagem?", type: "multi_select", options: ["Realiza", "Encaminha", "Não Se Aplica"], tags: { "Realiza": ["compostagem_propria", "residuos"], "Encaminha": ["compostagem_terceiros", "residuos"] }, sortOrder: 8 },
    { code: "res_09", questionNumber: "9", text: "A unidade está sujeita à elaboração de inventário de resíduos sólidos?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["inventario_residuos", "residuos"] }, sortOrder: 9 },
    { code: "res_10", questionNumber: "10", text: "A unidade gera resíduos da construção civil?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["residuos_construcao_civil", "residuos"] }, sortOrder: 10 },
    { code: "res_11", questionNumber: "11", text: "A unidade possui aterro sanitário ou controlado?", type: "multi_select", options: ["Não Se Aplica", "Aterro Sanitário", "Aterro Controlado", "Aterro Industrial"], tags: { "Aterro Sanitário": ["possui_aterro_sanitario"], "Aterro Controlado": ["possui_aterro_controlado"], "Aterro Industrial": ["possui_aterro_industrial"] }, sortOrder: 11 },
    { code: "res_12", questionNumber: "12", text: "A unidade gera resíduos perigosos conforme classificação prevista na NBR 10004?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["residuos_perigosos_nbr10004", "residuos"] }, sortOrder: 12 },
    { code: "res_13", questionNumber: "13", text: "A unidade realiza a importação de algum tipo de resíduo?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["importacao_residuos", "residuos"] }, sortOrder: 13 },
    { code: "res_14", questionNumber: "14", text: "A unidade realiza a exportação de algum tipo de resíduo?", type: "single_select", options: ["Sim", "Não"], tags: { "Sim": ["exportacao_residuos", "residuos"] }, sortOrder: 14 },
  ],
};

const equipamentos: ThemeDef = {
  code: "equipamentos",
  name: "Equipamentos",
  description: "Questões sobre equipamentos, máquinas, radiação, combate a incêndio, elevadores e proteção atmosférica",
  sortOrder: 10,
  questions: [
    { code: "eq_01", questionNumber: "1", text: "A unidade possui medidores de gás natural, biometano e GLP (quando em sua fase gasosa)?", type: "single_select", options: ["Sim", "Não"], tags: { "Sim": ["medidores_gas", "equipamentos"] }, sortOrder: 1 },
    { code: "eq_02", questionNumber: "2", text: "A empresa utiliza 'drone' para fins de controle ambiental e mapeamento aéreo tais como: barragem, floresta, reservas aquáticas, etc.?", type: "single_select", options: ["Não se aplica", "Sim"], tags: { "Sim": ["drone_ambiental", "equipamentos"] }, sortOrder: 2 },
    { code: "eq_03", questionNumber: "3", text: "A unidade possui tanques metálicos de armazenamento?", type: "single_select", options: ["Sim", "Não se aplica"], tags: { "Sim": ["tanques_metalicos", "equipamentos"] }, sortOrder: 3 },
    { code: "eq_04", questionNumber: "4", text: "A unidade possui caldeiras?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["caldeiras", "equipamentos", "nr13"] }, sortOrder: 4 },
    { code: "eq_05", questionNumber: "5", text: "Existem fontes de radiação ou há geração de rejeitos radioativos?", type: "multi_select", options: ["Não Se Aplica", "Fonte Ionizante (ex: Equipamentos Gamagrafia, Raio-x, Radioativos Em Geral).", "Fonte Não Ionizante (ex: Solda)", "Geração de Rejeitos Radioativos"], tags: { "Fonte Ionizante (ex: Equipamentos Gamagrafia, Raio-x, Radioativos Em Geral).": ["radiacao_ionizante", "cnen"], "Fonte Não Ionizante (ex: Solda)": ["radiacao_nao_ionizante"], "Geração de Rejeitos Radioativos": ["rejeitos_radioativos", "cnen"] }, sortOrder: 5 },
    { code: "eq_06", questionNumber: "6", text: "A unidade realiza a manutenção de equipamentos e maquinários em suas instalações?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["manutencao_equipamentos"] }, sortOrder: 6 },
    { code: "eq_07", questionNumber: "7", text: "A unidade possui vasos sob pressão?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["vasos_pressao", "nr13"] }, sortOrder: 7 },
    { code: "eq_07_1", questionNumber: "7.1", text: "A empresa utiliza vasos sob pressão ou caldeiras de fabricação seriada (em série)?", type: "single_select", options: ["Sim", "Não se Aplica"], conditionalOn: "eq_07", conditionalValue: "Sim", tags: { "Sim": ["vasos_pressao_seriados"] }, sortOrder: 8 },
    { code: "eq_07_2", questionNumber: "7.2", text: "A unidade possui serviço próprio de inspeção de equipamentos - SPIE?", type: "single_select", options: ["Sim", "Não Se Aplica"], conditionalOn: "eq_07", conditionalValue: "Sim", tags: { "Sim": ["spie_inspecao"] }, sortOrder: 9 },
    { code: "eq_08", questionNumber: "8", text: "Quais as máquinas/equipamentos são utilizados na unidade:", type: "multi_select", options: ["Motores elétricos trifásicos", "Prensas e similares", "Cestas aéreas ou cestos acoplados para elevação de pessoas e realização de trabalho em altura", "Máquinas e implementos para uso agrícola e florestal", "Injetoras de materiais plásticos", "Máquinas para açougue, mercearia, bares e restaurantes (serra de fita, amaciador de bife e moedor de carne)", "Motosserras", "Transportadores de materiais", "Gruas", "Cestos suspensos", "Moedor de carne (Máquina para açougue - NR 12)", "Amaciador de bife (Máquina para açougue - NR 12)", "Moinho para farinha de rosca (Máquina de panificação - NR-12)", "Serra de fita (Máquina para açougue - NR 12)", "Fatiadoras para pães (Máquina de panificação - NR-12)", "Modeladoras (Máquina de panificação - NR-12)", "Laminadoras (Máquina de panificação - NR-12)", "Cilindros (Máquina de panificação - NR-12)", "Batedeira (Máquina de panificação - NR-12)", "Amassadeira (Máquina de panificação - NR-12)", "Não Se Aplica"], tags: { "Prensas e similares": ["prensas", "nr12"], "Motosserras": ["motosserras", "nr12"], "Gruas": ["gruas", "nr12"], "Injetoras de materiais plásticos": ["injetoras_plastico", "nr12"], "Cestas aéreas ou cestos acoplados para elevação de pessoas e realização de trabalho em altura": ["cestas_aereas", "trabalho_altura"] }, sortOrder: 10 },
    { code: "eq_09", questionNumber: "9", text: "Existem na empresa estações rádio base (ERB's) fixas de telecomunicação?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["estacoes_radio_base", "telecomunicacoes"] }, sortOrder: 11 },
    { code: "eq_10", questionNumber: "10", text: "A unidade possui/instala torres de energia elétrica, antenas, mastros, linhas elétricas de transmissão próximo a aeroportos?", type: "single_select", options: ["Sim", "Não"], tags: { "Sim": ["torres_energia_aeroporto"] }, sortOrder: 12 },
    { code: "eq_11", questionNumber: "11", text: "Quais os equipamentos de combate a incêndio?", type: "multi_select", options: ["Porta Corta-fogo", "Mangueiras", "Hidrante", "Sistema de Proteção Por Espuma", "Extintor", "Iluminação de Emergência", "Chuveiros Automáticos", "Alarme", "Escada de Segurança", "Mangote Ou Mangotinho", "Não Se Aplica", "Sistema Ou Medidas de Controle de Fumaça", "Sistema Fixo de Gases"], tags: { "Hidrante": ["hidrante", "combate_incendio"], "Chuveiros Automáticos": ["sprinklers", "combate_incendio"], "Sistema Fixo de Gases": ["sistema_fixo_gases", "combate_incendio"] }, sortOrder: 13 },
    { code: "eq_12", questionNumber: "12", text: "Existe SPDA sistema de proteção contra descargas atmosféricas?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["spda", "protecao_atmosferica"] }, sortOrder: 14 },
    { code: "eq_13", questionNumber: "13", text: "Existe projeto de combate e prevenção a incêndios aprovado pelo Corpo de Bombeiros - PCPI?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["pcpi_bombeiros", "combate_incendio"] }, sortOrder: 15 },
    { code: "eq_14", questionNumber: "14", text: "Existem elevadores para transporte de pessoas?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["elevador_pessoas"] }, sortOrder: 16 },
    { code: "eq_15", questionNumber: "15", text: "Existem elevadores para transporte de carga?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["elevador_carga"] }, sortOrder: 17 },
    { code: "eq_16", questionNumber: "16", text: "Existe aeródromo na unidade?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["aerodromo"] }, sortOrder: 18 },
    { code: "eq_17", questionNumber: "17", text: "A unidade possui mecanismos de desenvolvimento limpo - MDL?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["mdl", "desenvolvimento_limpo"] }, sortOrder: 19 },
    { code: "eq_18", questionNumber: "18", text: "A unidade importa máquinas ou maquinismos com risco de periculosidade?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["importacao_maquinas_perigosas"] }, sortOrder: 20 },
    { code: "eq_19", questionNumber: "19", text: "Existem geladeiras na unidade?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["geladeiras"] }, sortOrder: 21 },
    { code: "eq_20", questionNumber: "20", text: "A unidade realiza jateamento de areia a seco em algum de seus processos?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["jateamento_areia", "saude_trabalhador"] }, sortOrder: 22 },
    { code: "eq_21", questionNumber: "21", text: "A unidade utiliza aparelhos de comunicação emissores de radiofrequência, nas suas atividades?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["radiofrequencia", "telecomunicacoes"] }, sortOrder: 23 },
    { code: "eq_22", questionNumber: "22", text: "A unidade possui cabine audiométrica?", type: "single_select", options: ["Sim", "Não Se Aplica"], tags: { "Sim": ["cabine_audiometrica", "saude_trabalhador"] }, sortOrder: 24 },
  ],
};

export async function seedQuestionnaire() {
  await seedTheme(instalacoes);
  await seedTheme(produtosInsumos);
  await seedTheme(produtosFlorestais);
  await seedTheme(combustiveisInflamaveis);
  await seedTheme(produtosQuimicos);
  await seedTheme(recursosHidricos);
  await seedTheme(residuos);
  await seedTheme(equipamentos);
}
